mexc:
  web:
    token: ${MEXC_TOKEN}
  asset:
    exclude: btc,eth,mx,usdt

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000